### ISSUE TITLE
TypeError: must be real number, not str

### ISSUE THREAD

**Issue by alvinak** [marcodebe/dicom-ecg-plot#12]
I am getting following error while running dicom-ecg-plot.exe program on windows
Kindly anyone help me to fix this issue 
Sample file is attached here with for the reference

>dicom-ecg-plot.exe C:\ecg.dcm  --layout 6x2 --output c:\result.png`

```
[ecg.zip](https://github.com/marcodebe/dicom-ecg-plot/files/8012811/ecg.zip)

Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "dicom-ecg-plot.py", line 62, in <module>
  File "dicom-ecg-plot.py", line 39, in convert
  File "ecg\ecg.py", line 588, in draw
  File "ecg\ecg.py", line 456, in print_info
  File "ecg\ecg.py", line 367, in legend
TypeError: must be real number, not str
[10348] Failed to execute script 'dicom-ecg-plot' due to unhandled exception!
```

**Comment by marcodebe** [comment]
Version 1.3.3 should have fixed this error.  I did the tests with your file (ecg.zip): version 1.3.3 works, previous version fails.
